# The URL the site will be built for
base_url = "https://anders.conbere.org"
theme = "anemone"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false
generate_feed = true
build_search_index = false
feed_filename = "atom.xml"

taxonomies = [
    { name = "tags", feed = true},
]


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
favoicon = ""
